platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

# inhibit_all_warnings!
use_frameworks!

target 'FailableExample' do
  pod 'Failable', :path => '..'
  pod 'Alamofire', '~> 4.5.1'
  pod 'AlamofireImage', '~> 3.3'
  pod 'ObjectMapper', '~> 3.0'
end

target 'FailableTests' do
  pod 'Failable', :path => '..'
end
